### ISSUE TITLE
MusicNet model weights

### ISSUE THREAD

**Issue by KyloRen1** [LUMII-Syslab/RSE#1]
Hello. Do you provide pretrained MusicNet model weights? And if so, where it is possible to download them? Thanks!

**Comment by AndisDraguns** [comment]
We currently do not have any saved pretrained models for music transcription. However, training the model on your own should not take more than a couple of days on a single GPU. If we end up training more models we can let you know and share the weights.

**Comment by KyloRen1** [comment]
@AndisDraguns thank you. Will much appreciate it.

**Comment by AndisDraguns** [comment]
We have added the weights of a pretrained MusicNet model to the repository in the `trained_model_m8192F1` directory.
