### ISSUE TITLE
Do you provide pretrained MusicNet model weights? 

### ISSUE THREAD

**Issue by sheng-zhong** [LUMII-Syslab/RSE#3]

**Comment by AndisDraguns** [comment]
We have added the weights of a pretrained MusicNet model to the repository in the `trained_model_m8192F1` directory.

**Comment by sheng-zhong** [comment]
> We have added the weights of a pretrained MusicNet model to the repository in the `trained_model_m8192F1` directory.

thank u very much.
but i dont know how to convert ckpt to pb file or onnx file
