### ISSUE TITLE
I want to deploy musicnet to mobile, but I don't know how to convert trained ckpt to tflite. please give me some helps

### ISSUE THREAD

**Issue by sheng-zhong** [LUMII-Syslab/RSE#4]

**Comment by AndisDraguns** [comment]
This might be useful for converting from the checkpoint format: https://github.com/onnx/tensorflow-onnx

**Comment by sheng-zhong** [comment]
> This might be useful for converting from the checkpoint format: https://github.com/onnx/tensorflow-onnx

I can't find the input and output of the model
